name: Frontend CI/CD

on:
  push:
    branches: [main] # Change this to the branch where your frontend code resides
  pull_request:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npx jest -- --watchAll=false --coverage

    - name: Build Project
      run: npm run build

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25 # Use a valid version (v25 or v26)
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./ # Adjust if your frontend code is in a subdirectory
